version: '3.8'

services:
    ubuntu:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                TAG: 22.04
        image: plane:22.04
        hostname: ubuntu
        env_file:
            - devcontainer.env
