backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: src/img
public_folder: /img
locale: ja
collections:
  - name: blog
    label: ブログ(2022年)
    create: true
    folder: src/posts/blogs/2022
    slug: "{{month}}-{{day}}_{{publishedPath}}"
    fields:
      - { label: 記事のタイトル, name: title, widget: string }
      - { label: 公開パス, name: publishedPath, widget: string, pattern: ["^[a-z0-9-]+$", "英小文字、数字+ハイフンのみ"] }
      - { label: 執筆者, name: author, widget: string, pattern: ["^[a-z-]+$", "英小文字のみ"]}
      - { label: 公開日, name: date, widget: date, date_format: YYYY-MM-DD, format: YYYY-MM-DD }
      - { label: 本文, name: body, widget: markdown }
      - label: リンク
        name: permalink
        widget: hidden
        default: "/blogs/{{ page.date | date: '%Y/%m/%d' }}/{{ publishedPath }}/"
      - label: タグ
        name: tags
        widget: list
        allow_add: true
        max: 10
        default: [post, 2022年]
  - name: settings
    label: 設定
    files:
      - name: site
        label: サイト全般
        file: src/_data/site.json
        editor:
          preview: false
        fields:
          - { label: サイト名, name: siteName, widget: string }
          - { label: サイト説明, name: siteDescription, widget: string }
          - { label: サイト運営者, name: authorName, widget: string }
          - { label: Twitterアカウント, name: twitterUsername, widget: string }
  - name: contributors
    label: 記事執筆者
    files:
      - name: github
        file: src/_data/contributors.json
        label: 執筆者名とGitHubアカウント紐付け
        editor:
          preview: false
        fields:
          - name: contributors
            label: 執筆者
            summary: "{{fields.name}} -> {{fields.github}}"
            widget: list
            fields:
              - { label: 名前, name: name, widget: string, pattern: [ "^[a-z]+-[a-z]+$", "英小文字(区切りはハイフン)" ] }
              - { label: GitHubアカウント, name: github, widget: string }


