const { Configuration, OpenAIApi } = require("openai");

const configuration = new Configuration({
  apiKey: process.env.OPENAI_API_KEY
});
const openai = new OpenAIApi(configuration);

async function ask(prompt) {
  try {
    const resp = await openai.createChatCompletion({
      model: "gpt-3.5-turbo",
      messages: prompt,
      max_tokens: 2048,
      temperature: 0.7
    });
    if (process.env.DEBUG) console.log("result", resp);
    console.log(`課金トークン消費量: ${JSON.stringify(resp.data.usage)}`);
    return resp.data.choices[0].message.content;
  } catch (e) {
    console.log(e.response.data);
    return "";
  }
}

module.exports.jargon = async function() {
  console.log("fetch jargon...");
  try {
    let prompt = {
      content: `ITデベロッパーがプログラミングで使うジャーゴンで、笑ってしまうくらい面白いものを10個改行区切りで出力してください。
順番や「はい」や「わかりました」等の返事、ジャーゴンの説明は不要です。
`,
      role: "user"
    };
    const message = await ask([prompt]);
    console.log(message);

    const arr = message.split('\n').filter(x => !!x).map(x => x.replace(/\d+\. /, ''));
    const i = Math.floor(Math.random() * arr.length);
    const target = arr[i];
    const result = await ask([
      prompt, {
        role: "assistant",
        content: message,
      }, {
        role: "user",
        content: `${target}についてその内容を説明してください。
以下の制約事項を守ってください。

- Speak in Japanese
- 最初にそのジャーゴンの説明をする
-「はい」や「わかりました」等の返事はしない
- 「です」「ます」等の敬語は使わない
- AI Chatの一人称は「豆香」を使う
- Conversation with User as your best friend. 
- Userのことは「あなた」と呼ぶ
- 最後に使用例をジョークを交えて話す
`
      }
    ]);

    return `<div>
    <fieldset class="chatgpt-jargon">
      <legend><img alt="mameka" src="/img/logo/mameka6_30.png">豆香のIT豆知識(generated by ChatGPT)</legend>
      <div>今日の言葉: ${target}</div>
      <div>${result.replaceAll(/\r?\n/g, '<br />')}</div>
      <div>※本コラムはChatGPTで自動生成したものです。内容に誤りがある可能性があります。</div>
    </fieldset>
  </div>`;
  } catch (e) {
    console.log({ e });
    return "";
  }
};
