[lint]
model = "gpt-3.5-turbo"
max_token = 1024
temperature = 0
prompt = """以下の文章(マークダウン)で以下の観点でチェックしてください。

- スペルミスがないか
- 冗長な表現がないか
- 前後関係で矛盾していないか
- 読みにくい文章でないか

チェック結果は観点ごとに、箇条書きでOKまたはNGを出力し、NG部分はその理由を出力してください。

例)
- スペルミスがないか: OK
- 冗長な表現がないか: NG
- XXXXXXの部分に誤りがあります。

なお、コードスニペット部分についてはチェック対象外です。"""

[scoring]
model = "gpt-3.5-turbo"
# max_token = 1024
temperature = 0
prompt = "以下の記事の内容をレビューして、10点満点で採点してください。改善ポイントがあればその内容を教えて下さい。"