name: generate-gpt-column

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create Branch for GPT generated page
        id: create-gpt-branch
        run: |
          BRANCH=feature/$(date +"%Y-%m-%d-%H%M%S")-gpt
          git checkout -b $BRANCH
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.OS }}-node-${{ hashFiles('scripts/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install
        run: |
          cd ${GITHUB_WORKSPACE}/scripts
          npm ci

      - name: Update page for GPT generated column
        id: update-for-gpt-column
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SLACK_CHANNEL_ID: ${{ vars.MAIN_SLACK_CHANNEL_ID }}
        run: |
          set -eu
          cd ${GITHUB_WORKSPACE}/scripts
          npm run generate:column
          git add ${GITHUB_WORKSPACE}/src/_data
          if ! git diff-index --quiet HEAD --; then
            echo "require commit & push"
            git status -sb
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit report
        if: steps.update-for-gpt-column.outputs.changed == 'true'
        run: |
          set -eu
          git config --local user.email "github-actions@mamezou.com"
          git config --local user.name "github-actions"
          git commit -m "chore: Add GPT generated column"
          git push -u origin ${{ steps.create-gpt-branch.outputs.branch }}

      # https://github.com/marketplace/actions/github-pull-request-action
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: ${{ steps.create-gpt-branch.outputs.branch }}
          pr_title: "Update GPT column by github-actions"
          pr_reviewer: kudoh
          pr_body: "Check the GPT generated column."
