name: generate-weekly-ranking

on:
  schedule:
    - cron: '0 15 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Branch for translation
        id: create-feature-branch
        run: |
          BRANCH=feature/$(date +"%Y-%m-%d")-translate
          git switch -c $BRANCH
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT

      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.OS }}-node-${{ hashFiles('scripts/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install
        run: |
          cd ${GITHUB_WORKSPACE}/scripts
          npm ci

      - name: Translate latest articles
        id: translate-latest-articles
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ vars.MAIN_SLACK_CHANNEL_ID }}
        run: |
          set -eu
          cd ${GITHUB_WORKSPACE}/scripts
          npm run translate:en
          git add ${GITHUB_WORKSPACE}/src/en
          if ! git diff-index --quiet HEAD --; then
            echo "require commit & push"
            git status -sb
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit report
        if: steps.translate-latest-articles.outputs.changed == 'true'
        run: |
          set -eu
          git config --local user.email "github-actions@mamezou.com"
          git config --local user.name "github-actions"
          git commit -m "feat: Add English-translated articles"
          git push -u origin ${{ steps.create-feature-branch.outputs.branch }}

      # https://github.com/marketplace/actions/github-pull-request-action
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: ${{ steps.create-feature-branch.outputs.branch }}
          pr_title: "[no-image] Add English-translated articles"
          pr_reviewer: kudoh
          pr_body: "Check auto English-translated articles."

